rubliki/urls.py
from django.conf.urls import patterns, include, url
from rubliki_1.views import *
# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('rubliki_1.views',
    # Examples:
    # url(r'^$', 'rubliki.views.home', name='home'),
    # url(r'^rubliki/', include('rubliki.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^$', LoginView.as_view(), name='login'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^registration/$', RegistrationView.as_view(), name='registration'),

    url(r'^cabinet/$', CabinetView.as_view(), name='cabinet'),

    url(r'^my_billings/$', BillingView.as_view(), name='billing'),
    url(r'^my_billings/add_new_billing/$', AddBillingView.as_view(), name='add-new-billing'),

    url(r'^my_categories/$', CategoryView.as_view(), name='category'),
    url(r'^my_categories/add_new_category/$', AddCategoryView.as_view(), name='add-new-category'),
    #
    # url(r'^my_categories/(?P<category_name>\w+)/my_subcategories/$', SubcategoryView.as_view(), name='subcategory'),
    # url(r'^my_categories/(?P<category_name>\w+)/my_subcategories/add_new_subcategory/$', AddSubcategoryView.as_view(), name='add-new-subcategory'),

    url(r'^transaction/$', TransactionView.as_view(), name='transaction'),
    url(r'^transaction/transfer/$', TransferView.as_view(), name='transfer'),

    url(r'^statement/$', StatementView.as_view(), name='statement'),
    url(r'^grafiki/$', GrafikiView.as_view(), name='grafiki'),

    url(r'^edit/$', EditProfileView.as_view(), name='edit'),


    # url(r'^register_ok/', RegistrationCompleteView.as_view(), name='register_ok'),
    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

rubliki_1/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, UserManager
from django.utils import timezone
from .consts import *


class User(AbstractBaseUser):
    username = models.CharField(max_length=256, unique=True)
    email = models.CharField(max_length=256)
    first_name = models.CharField(max_length=256)
    last_name = models.CharField(max_length=256)
    birth_date = models.DateField(default='1900-01-01')

    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)

    objects = UserManager()
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['password', 'email']


class Currency(models.Model):
    currency = models.SmallIntegerField(choices=CURRENCY_CHOICES)


class BillingTypes(models.Model):
    billing_type = models.SmallIntegerField(choices=BILLING_TYPE_CHOICES)


class Billing(models.Model):
    user = models.ForeignKey(User)
    billing_name = models.CharField(max_length=256)
    billing_type = models.ForeignKey(BillingTypes)
    currency = models.ForeignKey(Currency)
    money = models.FloatField(blank=True, default=0)


class CategoryTypes(models.Model):
    category_type = models.SmallIntegerField(choices=CATEGORY_TYPE_CHOICES)


class Category(models.Model):
    category_name = models.CharField(max_length=256)
    user = models.ForeignKey(User)
    category_type = models.ForeignKey(CategoryTypes)


# class Subcategory(models.Model):
#     category = models.ForeignKey(Category)
#     subcategory_name = models.CharField(max_length=256)


class TransactionType(models.Model):
    transaction_type = models.SmallIntegerField(choices=TRANSACTION_TYPE_CHOICES)


class Transaction(models.Model):
    user = models.ForeignKey(User)
    billing = models.ForeignKey(Billing)
    transaction_type = models.ForeignKey(TransactionType)
    category = models.ForeignKey(Category)
#    subcategory = models.ForeignKey(Subcategory)
    money = models.FloatField(default=0)
    datetime = models.DateTimeField()
    comment = models.TextField()

templates/add-new-billing.html
<!DOCTYPE html>
{% extends "base.html" %}
<html>
<head>
    <title>Добавление нового счета</title>
</head>
<body>
{% block content %}
    <h4>Добавляем новый счет</h4>

    <form method="post">{% csrf_token %}
        Название:<br/> <input name="billing_name" type="text"> <br/><br/>

        Тип счета:<br/>
        {% for i in billing_type %}
             {{ i.get_billing_type_display() }}
            <input name="billing_type" type="radio" value="{{ i.id }}"><br/>
        {% endfor %}<br/>

        Валюта:<br/>
        {% for j in currency %}
            {{ j.get_currency_display() }}
            <input name="currency" type="radio" value="{{ j.id }}"><br/>
        {% endfor %}<br/>

        Сколько денег сейчас на счете: <br/>
        <input name="money" type="number"><br/><br/>

        <input type="submit" value="create">


    </form>

{% endblock content %}
</body>
</html>

templates/add-new-category.html
<!DOCTYPE html>
{% extends "base.html" %}
<html>
<head>
    <title>New category</title>
</head>
<body>
{% block content %}
Добавляем новую категорию

<form method="post">{% csrf_token %}
    Название:<input name="category_name" type="text"> <br/>
    Тип категории:

    {% for i in category_type %}
             {{ i.get_category_type_display() }}
            <input name="category_type" type="radio" value="{{ i.id }}"><br/>
        {% endfor %}


    <br/>
    <input type="submit" value="create">
</form>
{% endblock content %}
</body>
</html>

templates/add-new-subcategory.html
<!DOCTYPE html>
{% extends "base.html" %}
<html>
<head>
    <title></title>
</head>
<body>
{% block content %}
Добавляем новую подкатегорию
<br/><br/>
<br/>тестовый вывод названия категории -- {{ category_name }}
<br/><br/>

<form method="post">{% csrf_token %}

    Название:<br/> <input name="subcategory_name" type="text"> <br/><br/>
    <input type="submit" value="create">
</form>
{% endblock content %}
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
{%  block head %}
    <head>
        {# Подключение .css  #}
        <link type="text/css" href="http://bootstrap-ru.com/assets/css/bootstrap.css" rel="stylesheet"/>

        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
        {# Подключение javascript #}
        {#  <script type="text/javascript" src="http://code.jquery.com/jquery-migrate-1.1.1.min.js"></script>#}
        <script type="text/javascript" src="http://code.jquery.com/jquery-2.0.0.js"></script>

        <script type="text/javascript" src="bootstrap-ru.com/assets/js/bootstrap.js"></script>
        <script type="text/javascript" src="http://bootstrap-ru.com/assets/js/jquery.js"></script>
        <script type="text/javascript" src="http://bootstrap-ru.com/assets/js/bootstrap-dropdown.js"></script>
        <script type="text/javascript" src="http://bootstrap-ru.com/assets/js/bootstrap-popover.js"></script>
        <script type="text/javascript" src="http://bootstrap-ru.com/assets/js/bootstrap-modal.js"></script>
        <script type="text/javascript" src="http://bootstrap-ru.com/assets/js/bootstrap-tooltip.js"></script>
        <script type="text/javascript" src="http://bootstrap-ru.com/assets/js/bootstrap-collapse.js"></script>
        <script type="text/javascript" src="http://bootstrap-ru.com/assets/js/bootstrap-scrollspy.js"></script>
        <script type="text/javascript" src="http://bootstrap-ru.com/assets/js/bootstrap-alert.js"></script>

{#          <script type="text/javascript" src="http://www.xiper.net/examples/js-plugins/forms/autoresize/js/autoresize-mod.jquery.js"></script>#}

        <title></title>
    </head>
{% endblock %}

{% block wrapper %}
    {% block header %}
        <div class="container">
        <div class="navbar">
            <div class="navbar-inner">
                <div class="nav-collapse collapse">
                    <p class="navbar-text pull-right">
                        {{ user.username }}
                        {% if user.first_name and user.last_name  %}
                            ({{ user.first_name }} {{ user.last_name }})
                        {% endif %}
                    </p>
                    <ul class="nav">

                        <li class="dropdown">
                            <a class="dropdown-toggle" id="drop4" role="button" data-toggle="dropdown" href="#">Кабинет <b class="caret"></b></a>
                            <ul id="menu1" class="dropdown-menu" role="menu" aria-labelledby="drop4">
                                <li><a href="/cabinet">Мой кабинет</a></li>
                                <li><a href="/edit">Редактировать мой кабинет</a></li>
                            </ul>
                        </li>

                        <li class="dropdown">
                            <a class="dropdown-toggle" id="drop4" role="button" data-toggle="dropdown" href="#">Счета <b class="caret"></b></a>
                            <ul id="menu1" class="dropdown-menu" role="menu" aria-labelledby="drop4">
                                <li><a href="/my_billings">Мои счета</a></li>
                                <li><a href="/my_billings/add_new_billing">Добавить новый счет</a></li>
                            </ul>
                        </li>

                        <li class="dropdown">
                            <a class="dropdown-toggle" id="drop4" role="button" data-toggle="dropdown" href="#">Категории <b class="caret"></b></a>
                            <ul id="menu1" class="dropdown-menu" role="menu" aria-labelledby="drop4">
                                <li><a href="/my_categories">Мои категории</a></li>
                                <li><a href="/my_categories/add_new_category">Добавить новую категорию</a></li>
                            </ul>
                        </li>

                        <li class="dropdown">
                            <a class="dropdown-toggle" id="drop4" role="button" data-toggle="dropdown" href="#">Транзакции <b class="caret"></b></a>
                            <ul id="menu1" class="dropdown-menu" role="menu" aria-labelledby="drop4">
                                <li><a href="/transaction">Провести транзакцию (приход/расход)</a></li>
                                <li><a href="/transaction/transfer">Провести трансфер</a></li>
                            </ul>
                        </li>

                        <li><a href="/statement">Статистика</a></li>
                        <li><a href="/grafiki">Графики</a></li>
                        <li><a href="/logout">Выход</a></li>
                    </ul>
                </div>
            </div>
        </div>
    {% endblock %}

{%  block body %}
    <body>

    {% block data %}
        {% block page %}

            <div class="row">
                <div class="span1">
                    {% block left %}
                        <p></p>
                    {% endblock %}
                </div>

                <div class="span10">
                    {% block content %}
                        <p></p>
                    {% endblock %}
                </div>

                <div class="span1">
                    {% block right %}
                        <p></p>
                    {% endblock %}
                </div>
            </div>
        {% endblock page %}

    {% endblock data %}

    </body>
{% endblock body %}
</div>
{% endblock wrapper %}
</html>

templates/cabinet.html
<!DOCTYPE html>
{% extends "base.html" %}
<html>
<head>
    <title>Личный кабинет</title>
</head>
<body>
{% block content %}

    Привет, {{ user.username }}!
    Пока что страница кажется не нужной. Возможно, на ней что то появится позже.
    Например, история последних операций по счетам.

{% endblock content %}
</body>
</html>

templates/categories.html
<!DOCTYPE html>
{% extends "base.html" %}
<html>
<head>
    <title>Мои категории</title>
</head>
<body>
{% block content %}

<h4>Список категорий</h4>


    <h5>Доход:</h5>
    <br/>
{% for i in user_categories_income %}
    <tr>
        <td>{{ i.category_name }}</td>
{#        <a href="{{ i.category_name }}/my_subcategories/">go</a>#}
        <br/>
    </tr>
{% endfor %}
    <br/><br/><br/>

    <h5>Расход:</h5>
    <br/>
{% for i in user_categories_outcome %}
    <tr>
        <td>{{ i.category_name }}</td>
{#        <a href="{{ i.category_name }}/my_subcategories/">go</a>#}
        <br/>
    </tr>
{% endfor %}

{% endblock content %}
</body>
</html>

templates/edit.html
<!DOCTYPE html>
{% extends "base.html" %}
<html>
<head>
    <title>Редактирование профиля</title>
</head>
<body>
{% block content %}
Редактируем профиль
{% endblock content %}
</body>
</html>

templates/grafiki.html
<!DOCTYPE html>
{% extends "base.html" %}
<html>
<head>
    <title>Графики</title>
</head>

<body>

{% block content %}
    <ul>
        <li><a id="result_chart_btn" href="/statement">ПОСМОТРЕТЬ ТАБЛИЦУ</a></li>
    </ul>
    <script type="text/javascript">
        $(function () {
            $('#container').highcharts({
                chart: {
                    type: 'line'
                },
                title: {
                    text: 'Расходы по категориям'
                },
                xAxis: {
                    categories:
                            [
                            {% for i in dsfgfgtg %}
                                {{ i }},
                            {% endfor %}
                            ]

{#                            ['Ольге',#}
{#                            'кв.пл.',#}
{#                            'питание',#}
{#                            'вкусности',#}
{#                            'проезд',#}
{#                            'сигареты',#}
{#                            'кафе работа',#}
{#                            'связь',#}
{#                            'детям',#}
{#                            'подарки',#}
{#                            'хозяйство',#}
{#                            'развлечения',#}
{#                            'аптека']#}
                },
                yAxis: {
                    title: {
                        text: 'RUR'
                    }
                },
                series: [{
                    name: '',
                    data:
                            [
                                {% for i in money %}
                                    {{ i }},
                                {% endfor %}
                            ]

{#                        [13000,#}
{#                        2411,#}
{#                        9414,#}
{#                        1749,#}
{#                        3350,#}
{#                        1719,#}
{#                        5058,#}
{#                        700,#}
{#                        457,#}
{#                        1268,#}
{#                        1264,#}
{#                        4449,#}
{#                        1291]#}
                }]
            });
        });
    </script>




<script src="http://code.highcharts.com/highcharts.js"></script>
<div id="container" style="height: 600px"></div>
{% endblock content %}
</body>
</html>

templates/login.html
<!DOCTYPE html>
{% extends "base.html" %}
<html>
    <head>
        <title>Welcome to Rubliki.ru!</title>
    </head>

    <body>
{% block content %}
        Welcome to Rubliki.ru!

        <form method="post">{% csrf_token %}
            <div><input id="id_username" name="login" type="text" onFocus="checkFocus(this, 'логин')" onBlur="checkBlur(this, 'логин')" /></div>
            <div><input id="id_password" name="password" type="password" onFocus="checkFocus(this, 'пароль')" onBlur="checkBlur(this, 'пароль')"/></div>
            <div><input class="btn btn-primary btn-small" type="submit" value="войти"/>
        </form>

        <a class="btn btn-primary btn-small"href="/registration">Создать новый аккаунт</a>
{% endblock content %}
    </body>
</html>

templates/registration.html
<!DOCTYPE html>
{% extends "base.html" %}
<html>
<head>
    <title>Регистрация нового пользователя</title>
</head>
<body>
{% block content %}
Добро пожаловать в Мир Рубликов!

<form method="post">{% csrf_token %}
    login: <input name="login" type="text"><br/>
    email: <input name="email" type="email"><br/>
    pass: <input name="password" type="password"><br/>
    confirm: <input name="password_confirm" type="password"><br/>
    name: <input name="first_name" type="text"><br/>
    last name: <input name="last_name" type="text"><br/>

    <input type="submit" value="Зарегистрироваться">

</form>
{% endblock content %}
</body>
</html>

templates/statement.html
<!DOCTYPE html>
{% extends "base.html" %}
<html>
<head>
    <title>
        Проведенные транзакции
    </title>
</head>

<body>

{% block content %}
    <br/>

    <ul>
        <li><a id="result_chart_btn" href="/grafiki">ПОСМОТРЕТЬ ГРАФИК</a></li>
    </ul>

    <select>
        <option value=""></option>
    </select>

    <table width="100%" align="left">
        <th>счет</th>
        <th>категория</th>
{#        <th>подкатегория</th>#}
        <th>деньги</th>
        <th>дата</th>
        <th>коммент</th>
        <th></th>
        <th></th>

        {% for i in transactions %}
            <tr align="center">
                <td>{{ i.billing.billing_name }} ({{ i.billing.billing_type.get_billing_type_display() }}) </td>

                <td>{{ i.category.category_name }}</td>
{#                <td>{{ i.subcategory.subcategory_name }}</td>#}
                <td>
                    {% if i.transaction_type.get_transaction_type_display() == 'income' %} + {% else %} - {% endif %}
                    {{ i.money }}
                    {{ i.billing.currency.get_currency_display() }}
                </td>
                <td>{{ i.datetime|date }}</td>
                <td>{{ i.comment }}</td>
            </tr>

        {% endfor %}
{#    <tr>#}
{#        <td></td>#}
{#        <td></td>#}
{#        <td></td>#}
{#        <td>итого получено:  {{ total_income }}</td>#}
{#        <td></td>#}
{#        <td></td>#}
{##}
{#    </tr>#}
{#    <tr>#}
{#        <td></td>#}
{#        <td></td>#}
{#        <td></td>#}
{#        <td>итого потрачено:  {{ total_spent }}</td>#}
{#        <td></td>#}
{#        <td></td>#}
{##}
{#    </tr>#}
    </table>

{% endblock content %}
</body>
</html>

templates/subcategories.html
{#<!DOCTYPE html>#}
{#{% extends "base.html" %}#}
{#<html>#}
{#<head>#}
{#    <title></title>#}
{#</head>#}
{#<body>#}
{#{% block content %}#}
{#<a href="/my_categories/{{ category_name}}/my_subcategories/add_new_subcategory/">Добавить новую подкатегорию</a>#}
{##}
{#<h4>Список подкатегорий вот этой категории - {{ category_name }}</h4>#}
{##}
{##}
{##}
{#{% for i in user_subcategories %}#}
{#    <tr>#}
{#        <td>{{ i.subcategory_name }}</td>#}
{#        <br/>#}
{#    </tr>#}
{#{% endfor %}#}
{##}
{#{% endblock content %}#}
{#</body>#}
{#</html>#}

templates/transaction.html
<!DOCTYPE html>
{% extends "base.html" %}
<html>
<head>
    <title></title>
</head>
<body>
{% block content %}
{#<br/>#}
{#Проводим транзакцию:<br/><br/>#}

<form method="post">{% csrf_token %}
    <table>
        <tr>
            <td>
                Тип транзакции:
            </td>
            <td>
                <select name="transaction_type">
                    {% for types in transaction_types %}
                        <option value="{{ types.id }}" >{{ types.get_transaction_type_display() }}</option>
                    {% endfor %}
                </select>
            </td>
        </tr>
        <tr>
            <td>
                Счет:
            </td>
            <td>
                <select name="billing_id">
                    {% for bill in my_billings %}
                        <option value="{{ bill.id }}" >{{ bill.billing_name }} ({{ bill.currency.get_currency_display() }} , {{ bill.billing_type.get_billing_type_display() }} )</option>
                    {% endfor %}
                </select>
                <br/>
            </td>
        </tr>
        <tr>
            <td>
                Категория:
            </td>
            <td>
                <select name="category_id">
                    {% for cat in my_categories %}
                        <option value="{{ cat.id }}" >{{ cat.category_name }}</option>
                    {% endfor %}
                </select>
            </td>
        </tr>
        <tr>
            <td>
                Сумма:</td><td> <input type="number" name="money"></td>
        </tr>
        <tr>
            <td>
            Комментарий:</td><td> <input type="text" name="comment"></tr>
        <tr>
            <td>
                <input class="btn btn-primary btn-small" type="submit" value="провести транзакцию">
            </td>
        </tr>
    </table>
</form>
{% endblock content %}
</body>
</html>

templates/transfer.html
<!DOCTYPE html>
{% extends "base.html" %}
<html>
<head>
    <title></title>
</head>
<body>
{% block content %}
    Перевод денег с одного счета на другой:<br/><br/>
    <form method="post">{% csrf_token %}

        С какого счета списать:<br/><br/>
        {% for bill in my_billings %}

            <input type="radio" name="billing_id_from" value={{ bill.id }}>{{ bill.billing_name }}
            (в валюте '{{ bill.currency.get_currency_display() }}')
            (тип счета '{{ bill.billing_type.get_billing_type_display() }}')

            <br/>


        {% endfor %}<br/>


        На какой счет начислить:<br/><br/>
        {% for bill in my_billings %}

            <input type="radio" name="billing_id_to" value={{ bill.id }}>{{ bill.billing_name }}
            (в валюте '{{ bill.currency.get_currency_display() }}')
            (тип счета '{{ bill.billing_type.get_billing_type_display() }}')

            <br/>


        {% endfor %}
        <br/><br/>
        Сколько денег перевести: <input type="number" name="money"><br/><br/>

        Ваш комментарий: <input type="text" name="comment"><br/><br/>
        <input type="submit" value="сделать перевод">

    </form>
{% endblock content %}
</body>
</html>